# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact/main/dbos-config.schema.json

database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: puppeteer_app
  connectionTimeoutMillis: 3000
  app_db_client: knex
  migrate:
    - echo "no migrations"
env:
  AWS_EXECUTION_ENV: 20.x
runtimeConfig:
  entrypoints:
    - dist/operations.js
